import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Explicit sidebar for the Lambda API docs. Authored by hand (rather than
 * autogenerated) so category order and labels stay deterministic.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/introduction',
        'getting-started/installation',
        'getting-started/quick-start',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'core-concepts/configuration',
        'core-concepts/routes-and-methods',
        'core-concepts/returning-responses',
        'core-concepts/route-prefixing',
        'core-concepts/path-parameters',
        'core-concepts/wildcard-routes',
        'core-concepts/namespaces',
        'core-concepts/execution-stacks',
        'core-concepts/debugging-routes',
      ],
    },
    {
      type: 'category',
      label: 'Request & Response',
      items: [
        'request-response/request-object',
        'request-response/response-object',
        'request-response/sending-responses',
        'request-response/headers-and-cookies',
        'request-response/redirects-and-cors',
        'request-response/caching-and-etags',
        'request-response/files-and-downloads',
      ],
    },
    {
      type: 'category',
      label: 'Middleware & Error Handling',
      items: [
        'middleware-errors/middleware',
        'middleware-errors/clean-up',
        'middleware-errors/error-handling',
      ],
    },
    {
      type: 'category',
      label: 'Logging',
      items: [
        'logging/overview',
        'logging/levels-and-format',
        'logging/serializers-and-detail',
        'logging/sampling',
      ],
    },
    {
      type: 'category',
      label: 'Deployment & Integrations',
      items: [
        'deployment/lambda-proxy-integration',
        'deployment/alb-integration',
        'deployment/api-gateway-routes',
        'deployment/compression',
        'deployment/cors-support',
        'deployment/persistent-connections',
      ],
    },
    {
      type: 'category',
      label: 'TypeScript',
      items: ['typescript/typescript-support'],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api-reference/app-configuration',
        'api-reference/request-properties',
        'api-reference/response-methods',
      ],
    },
  ],
};

export default sidebars;
