name: 'Pull Request'
on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  NPM_VERSION: latest

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]
    name: Node ${{ matrix.node }}
    steps:
      - name: 'Checkout latest code'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install latest npm
        run: |
          npm install -g npm@$NPM_VERSION &&
          npm --version &&
          npm list -g --depth 0
      - name: Install dependencies
        run: npm ci
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test

  lint:
    name: 'ESLint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint:check

  prettier:
    name: 'Prettier'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier
        run: npm run prettier:check
